### ISSUE TITLE
Log function can sometimes graph asymptotes

### ISSUE THREAD

**Issue by Valenciola** [makaip/mathematix#24]
As you can see in these pictures, Mathematix can correctly graph the function log base 5 of x, minding the asymptote at x = 0.

![Desmos log-base5ofx](https://github.com/makaip/mathematix/assets/93671200/e2dc1240-a771-4383-afa1-b9287eefb11f)
![Mathematix-logbase5ofx](https://github.com/makaip/mathematix/assets/93671200/04c39f26-08bd-4a3e-b33b-60c1161aeb4e)

However, for the function log base x of 5, Mathematix also graphs the asymptote along with the correct function (this asymptote is x = 1).

![Desmos log-basexof5](https://github.com/makaip/mathematix/assets/93671200/0fcc15f0-50ec-4c6d-9b32-78ab2492867d)
![Mathematix-logbasexof5](https://github.com/makaip/mathematix/assets/93671200/4314fa5e-961f-46ff-8a39-4b63f921db5b)

**Comment by AlexanderJCS** [comment]
Thanks for finding this. I'll fix this issue in the coming days when I have more time.

Note to future self: equate function to `-infinity` and `infinity` to find some asymptotes
