### ISSUE TITLE
Mathematix logo

### ISSUE THREAD

**Issue by AlexanderJCS** [makaip/mathematix#26]
A mathematix logo should be on the top left of the webpage. All mathematix logos are currently found in the `/assets/logos` directory.

The logo should be roughly where the red box is here:
![image](https://github.com/makaip/mathematix/assets/98898166/b0104011-c8fa-40ac-96fe-e81a840a6da3)

**Comment by AlexanderJCS** [comment]
This is a good first issue for someone with some HTML experience.

**Comment by Valenciola** [comment]
If he has time, maybe Jossaya can pick this one up?
