### ISSUE TITLE
Feature idea - graph the node individually

### ISSUE THREAD

**Issue by AlexanderJCS** [makaip/mathematix#27]
## Feature Idea

Selected nodes are graphed as if they are connected to the `output` node. This allows the user to understand how their function works in more detail.

How do you feel about this idea? @makaip @Valenciola

**Comment by Valenciola** [comment]
Do you mean like instead of the nodes being connected to the output node, they would just be graphed straight in output if we selected them?

**Comment by AlexanderJCS** [comment]
Yes, exactly that. It will also help with "debugging" larger node graphs. What do you think?

It could also be useful to graph it in another color if that makes it more clear to the user.

**Comment by Valenciola** [comment]
Note: in hex #ff3b65 (Salmon/Coral pink)
