### ISSUE TITLE
Nodule connections remain after node block is deleted

### ISSUE THREAD

**Issue by makaip** [makaip/mathematix#3]
When connecting two node blocks, the connections update, causing a line to be drawn between the two nodules.
![image](https://github.com/makaip/mathematix/assets/120488352/7b704e63-d325-447c-81cb-c04d7d4def3f)
Upon deleting the connected nodule, however, the line is still connected to where the nodule would have been. This is most possibly due to the fact that the nodule objects are still contained within the object it is connected to, despite the fact that the parent object (the node) has been deleted. 
![image](https://github.com/makaip/mathematix/assets/120488352/7c9a3e56-3df6-4926-9fcd-86ef8b7bd4c0)
However, the contents of the object are not modified, even when the screen is updated, allowing the user to drag around a node block connected to a nonexistent nodule.
![image](https://github.com/makaip/mathematix/assets/120488352/b571d1fe-dc29-4de5-a5bd-68dccba9093c)

**Comment by Valenciola** [comment]
On top of this, you are able to drag out into the editor without connecting to anything and the line will remain.

**Comment by Valenciola** [comment]
I'm not sure if this is relevant to the problem but you are unable to connect a value node to two output nodes (the line is erased); maybe seeing where this happens can help solve the problem with what happens when the user presses any of the deletion buttons.

**Comment by AlexanderJCS** [comment]
As-is, that's intentional. Otherwise there's really no way to change where the connection connects to.

In the future, it would be nice if we could connect an input node to multiple outputs. You could disconnect by re-connecting to the same output.

This should go in its own issue.

**Comment by AlexanderJCS** [comment]
Made a PR. Still needs a code review @makaip
