### ISSUE TITLE
QOL: shift + T and shift + U keybind

### ISSUE THREAD

**Issue by AlexanderJCS** [makaip/mathematix#35]
Currently you can do `shift + F` to create a new function node, `shift + R` to make a new input node, `shift + V` to make a new variable node, etc.

I propose two more keybinds:
1. `shift + T` for a new trig node block
2. `shift + U` for a new unary node block

This should be a relatively simple addition, but **please wait until I make my `events.js` refactor before making any changes. This will cause a merge conflict.**

The section to modify is the `window.addEventListener("keydown", (event) =>` event in the `editor/events.js` file.

**Comment by AlexanderJCS** [comment]
The code to modify is in `editor/events.js`: 
```js
let keyMap = {
        "Escape": hideMenu,
        "A": () => showMenu(endX, endY),
        "F": newFunction,
        "R": newInput,
        "C": newOutput,
        "V": newVariable,
    }

```
The functions being referenced are in `actions.js`

@Valenciola @jcamille2023 both of you don't have many contributions - do one of you want to take this on?

**Comment by Valenciola** [comment]
Sure I’ll take this one on if Jossaya doesn’t

**Comment by AlexanderJCS** [comment]
He DMed me this morning about information about it, but haven't seen anything since. I'll update you if you can do it instead

**Comment by jcamille2023** [comment]
That’s my bad I didn’t realize your refactor pull request was already merged

Sincerely,
Jossaya Camille
Student, FAU High School
________________________________
