### ISSUE TITLE
Cannot interact with very left of the screen

### ISSUE THREAD

**Issue by AlexanderJCS** [makaip/mathematix#40]
I can't interact with node blocks on the very left of the screen. This might be related to issue #38 or due to the recent addition of the Mathematix logo in the top-left corner.

**Comment by AlexanderJCS** [comment]
![image](https://github.com/makaip/mathematix/assets/98898166/d43d2fd7-dd7b-4fe7-8d60-ebad7cc60d16)

Roughly the line where I can't interact

**Comment by jcamille2023** [comment]
It is likely related to the addition of the logo. I added a logo-container positioned absolutely over the parent navbar. The issue is, its likely absolute over the entire document which is problematic. I will see how I can address it.
