### ISSUE TITLE
MAJORLY BROKEN !!! mildly complex graph throw a lot of errors

### ISSUE THREAD

**Issue by AlexanderJCS** [makaip/mathematix#46]
This graph here shows a lot of errors in the console and doesn't display properly. I can fix this tomorrow morning.

This needs to be fixed and merged ASAP

![image](https://github.com/makaip/mathematix/assets/98898166/ec2ab2cf-fe80-4345-9679-727b009f0d25)

**Comment by AlexanderJCS** [comment]
Potentially related: the preview of the Variable node (`x`) shows 0, instead of `y=x`

**Comment by jcamille2023** [comment]
We should probably make sure this is good before the uiclasses refactor.
